# Generated by Django 2.2.14 on 2020-07-14 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bets',
            name='owner',
        ),
        migrations.AddField(
            model_name='user',
            name='bets',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bets.Bets'),
        ),
    ]
