# Generated by Django 2.2.14 on 2020-07-14 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0002_auto_20200714_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bets',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='bets.Bets'),
        ),
    ]
