# Generated by Django 2.2.14 on 2020-07-14 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0003_auto_20200714_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='bets',
            name='owner',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='bets',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bets.Bets'),
        ),
    ]
