# Generated by Django 2.2.14 on 2020-07-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0003_auto_20200722_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bets',
            name='away_points',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bets',
            name='home_points',
            field=models.IntegerField(),
        ),
    ]
